### ISSUE TITLE
work.cost_domain_id_swap does not exist

### ISSUE THREAD

**Issue by lore-edencehealth** [RADar-AZDelta/Rabbit-in-a-Blender#100]
when processing the logic for cost table, src/riab/etl/sql_server/templates/etl/{omop_table}_merge.sql.jinja tries to do a left join.
LEFT OUTER JOIN [{{work_database_catalog}}].[{{work_database_schema}}].[{{column}}_swap] swap_fk{{ns.fk_counter}} on swap_fk{{ns.fk_counter}}.x = t.[{{column}}]
I can not find a place in the code where work.cost_domain_id_swap would be created so am wondering if this is a bug.

**Comment by pjlammertyn** [comment]
We havent used the cost table yet.
I will try with a dummy query to get it working.
