### ISSUE TITLE
workflow build_container

### ISSUE THREAD

**Issue by lore-edencehealth** [RADar-AZDelta/Rabbit-in-a-Blender#103]
Workflow for building a container seems to have changed.
There is no longer a container build for each tag but only for updates to main.
Not sure if this is a problem but using tag 'latest' to fetch the latest tagged version no longer works.

**Comment by pjlammertyn** [comment]
there is now a build for each tag, but it uses the hash in stead of the tag version

![image](https://github.com/user-attachments/assets/3e701c74-385c-4caf-899e-5bc3d1fe512e)

![image](https://github.com/user-attachments/assets/2d93f464-105a-49fc-9ddc-75ace85cf294)
