### ISSUE TITLE
riab -dq error

### ISSUE THREAD

**Issue by lore-edencehealth** [RADar-AZDelta/Rabbit-in-a-Blender#106]
sqlalchemy.exc.ProgrammingError: (pymssql.exceptions.ProgrammingError) (208, b"Invalid object name '[omop.dbo].[cdm_source'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")
[SQL: select * from [[omop].[dbo]].[cdm_source];]

running select * from [[omop].[dbo]].[cdm_source]; gives an error, 
replacing it by select * from [omop].[dbo].[cdm_source]; works so I think the extra brackets need to be removed from the code.

**Comment by pjlammertyn** [comment]
Can you give more detail where the error occurs.

**Comment by pjlammertyn** [comment]
More info on the square brackets: [Delimited identifiers](https://learn.microsoft.com/en-us/sql/relational-databases/databases/database-identifiers?view=sql-server-ver15#classes-of-identifiers)

**Comment by lore-edencehealth** [comment]
https://github.com/RADar-AZDelta/Rabbit-in-a-Blender/blob/main/src/riab/etl/sql_server/data_quality.py#L79
I think the problem is that the brackets are around the combination of schema.table which makes it think the dot is part of the table name.
