### ISSUE TITLE
RIAB: Performance RiAB & cost

### ISSUE THREAD

**Issue by kdenturc** [RADar-AZDelta/Rabbit-in-a-Blender#31]
@pjlammertyn running RiAB on measurement table alone has taken runtime approximate 15 to 20 minutes and at the end the cost went up to 10EUR, so today I've spent over 100EUR.
How can we optimize?

If I took the labo_usagi_csv file and diminished the rows from 6500 till 70, then runtime went to 3 minutes and cost was 0.91EUR
which is funner to work with.

Would it be an idea for performance and cost that we delete unchecked and flagged mappings? how can we do so?

tx!
please follow @sieldep

**Comment by sieldep** [comment]
De usagi files voor mzg diagnoses zijn bijvoorbeeld ook heel groot. Eventueel ook filteren op wanneer sourceFrequency 0 is? Dat deze niet in de usagi blijven staan?
