### ISSUE TITLE
RIAB: invalid concept domains condition_occurence

### ISSUE THREAD

**Issue by kdenturc** [RADar-AZDelta/Rabbit-in-a-Blender#33]
After running newest version of RiAB on rebased dev and command: riab --run-etl . -t condition_occurrence
there was following error
![image](https://github.com/RADar-AZDelta/Rabbit-in-a-Blender/assets/98580512/81a02f8d-4ae9-48a8-877a-3eea383635df)
after checking the mzg_auto_usagi.csv file, no other domain than condition was appearing, so this is strange
![image](https://github.com/RADar-AZDelta/Rabbit-in-a-Blender/assets/98580512/31cb1ad3-9b18-4353-8bde-3c881be85b06)

Could it be a capital issue Condition instead of condition??? 

@lbertelo01 @sieldep tx for following

**Comment by pjlammertyn** [comment]
Addeed extra info to the exception.
Now you can see that there is something wrong with the mapping!

![image](https://github.com/RADar-AZDelta/Rabbit-in-a-Blender/assets/1187178/b98ddbce-e0c2-4d48-a611-f1f77eb7d69f)
