### ISSUE TITLE
Check for non-standard codes in usagi files

### ISSUE THREAD

**Issue by sieldep** [RADar-AZDelta/Rabbit-in-a-Blender#43]
Would it be possible to add a check in riab, so that it gives an error or warning when non-standard concepts were chosen? 

We noticed that by updating the vocabularies to the most recent version, some concepts were changed to non-standard. It would be useful if riab would check for these codes.

**Comment by pjlammertyn** [comment]
solved in commit https://github.com/RADar-AZDelta/Rabbit-in-a-Blender/commit/d4b20ee2fb9dfbd849305f21f867293ea752fa4c
