### ISSUE TITLE
Suggestion for small change in table order of ETL 

### ISSUE THREAD

**Issue by lbertelo01** [RADar-AZDelta/Rabbit-in-a-Blender#48]
![image](https://github.com/RADar-AZDelta/Rabbit-in-a-Blender/assets/98480071/dd858705-839b-4319-814f-4586951692e4)

The vocabulary table should be one of the first tables to run, because if a table uses custom concepts, it checks if the vocabulary used (in our case AZDELTA) is present in the vocabulary table. With the order used now, we get a problem with the custom concepts in the fact_relationship table.

**Comment by pjlammertyn** [comment]
solved in commit https://github.com/RADar-AZDelta/Rabbit-in-a-Blender/commit/86147b3582a55d19e57514da75d713d1c653af53
