### ISSUE TITLE
DQD: typo in template query for BigQuery

### ISSUE THREAD

**Issue by lbertelo01** [RADar-AZDelta/Rabbit-in-a-Blender#57]
There seems to be a problem with some DQD queries in BigQuery

<img width="636" alt="image" src="https://github.com/RADar-AZDelta/Rabbit-in-a-Blender/assets/98480071/c26ebba0-a67b-48eb-be7f-1aafb7c92b58">

**Comment by pjlammertyn** [comment]
Dat zijn fouten in de OHDSI [SqlRender](https://github.com/OHDSI/SqlRender) library.
Ik ga kijken om betere logging toe te voegen, zodat de query ook in de log komt.
Zo kan ik issue openen bij SqlRender.

**Comment by hannevanl** [comment]
@pjlammertyn heb je de oplossing hier al uitgetest? https://github.com/OHDSI/SqlRender/issues/361 
Want het DQD heeft hele slechte resultaten doordat die queries niet werken
