### ISSUE TITLE
Update documentation --cleanup function

### ISSUE THREAD

**Issue by JensCardon** [RADar-AZDelta/Rabbit-in-a-Blender#72]
From the docs, running the --cleanup function will remove all data from OMOP tables. 

A as user I hesitated to run this command as I thought this might remove all uploaded vocabulary table data; which it doesn't.

Please update the description of the function.

![image](https://github.com/RADar-AZDelta/Rabbit-in-a-Blender/assets/24375456/d135be02-3156-49d8-944f-9cb9fc807d8c)

**Comment by pjlammertyn** [comment]
solved in commit https://github.com/RADar-AZDelta/Rabbit-in-a-Blender/commit/b44fda77de458a8b5bf083b0b9756078f94b1d2a
