### ISSUE TITLE
Note: event_id template joins on 'None_swap' work table

### ISSUE THREAD

**Issue by lbertelo01** [RADar-AZDelta/Rabbit-in-a-Blender#76]
![image](https://github.com/RADar-AZDelta/Rabbit-in-a-Blender/assets/98480071/08cd6533-ea80-4d88-8fe5-7c6b417841f9)

Events are however correctly defined: https://github.com/RADar-AZDelta/Rabbit-in-a-Blender/blob/main/src/riab/etl/cdm_5.4_events.json

During the execution of this [template](https://github.com/RADar-AZDelta/Rabbit-in-a-Blender/blob/main/src/riab/etl/bigquery/templates/etl/%7Bomop_table%7D_apply_event_columns.sql.jinja), a connection error arises.

![image](https://github.com/RADar-AZDelta/Rabbit-in-a-Blender/assets/98480071/702302ee-dcf0-47ef-9749-458631522aa1)

**Comment by pjlammertyn** [comment]
Is this not the result of a hickup in the internet connection to GCP? @lbertelo01

**Comment by pjlammertyn** [comment]
This comes because of filling in the wrong field with the referring table! Column note_event_field_concept_id should contain the table name and not column note_event_id!

![image](https://github.com/RADar-AZDelta/Rabbit-in-a-Blender/assets/1187178/980beb32-8347-4bd4-adaa-f6f6888018e6)
