### ISSUE TITLE
DQD: syntax error running PLAUSIBLE_AFTER_BIRTH check in DQ command

### ISSUE THREAD

**Issue by kdenturc** [RADar-AZDelta/Rabbit-in-a-Blender#83]
Running command riab --data-quality fails with syntax error

![image](https://github.com/RADar-AZDelta/Rabbit-in-a-Blender/assets/98580512/b6cb33db-5beb-4e34-acea-393f6ebb133a)

![image](https://github.com/RADar-AZDelta/Rabbit-in-a-Blender/assets/98580512/ea577513-a055-46af-be9d-e496a462d9a5)

**Comment by pjlammertyn** [comment]
same as https://github.com/RADar-AZDelta/Rabbit-in-a-Blender/issues/57, so will close
