### ISSUE TITLE
Source_to_concept_id, mogen niet in source_to_concept in omop komen

### ISSUE THREAD

**Issue by kdenturc** [RADar-AZDelta/Rabbit-in-a-Blender#85]
Source_to_concept aanpassen,  gezien dit non-standard zijn, is geen mapping!

**Comment by pjlammertyn** [comment]
Kim, correct:

The source to concept map table is recommended for use in ETL processes to maintain local source codes which are not available as Concepts in the Standardized Vocabularies, and to establish mappings for each source code into a **Standard Concept** as target_concept_ids that can be used to populate the Common Data Model tables.
