### ISSUE TITLE
SQL Server: can't connect to named instance with RiaB

### ISSUE THREAD

**Issue by rgoesseye** [RADar-AZDelta/Rabbit-in-a-Blender#91]
When using a named instance I can't connect to the database server in RiaB, this could be due to using a python module in RiaB which doesn't support named instances connections.

<img width="722" alt="riab_instance_sql_no_conn" src="https://github.com/user-attachments/assets/a779a957-db41-4053-bdac-0ecfd956dd94">

In the image above you can see the error that RiaB gives about being unable to connect. I tried different ways to write the server and the named instance -> (server//named_instance, server/named_instance, server\named_instance, ...) but it didn't work.

**Comment by JensCardon** [comment]
Riab connects to the database server using a sql authentication connection string, I don't think named instances are supported.

**Comment by pjlammertyn** [comment]
A possible solution could be not setting the port, when it is a named instance.
The downside for this, is that named instances can only sit on port 1433.
