### ISSUE TITLE
Error running riab --cleanup 

### ISSUE THREAD

**Issue by JensCardon** [RADar-AZDelta/Rabbit-in-a-Blender#92]
Running the riab --cleanup command results in foreignkey vialation errors for Azure SQL Server Databases.

Possible fix: replace TRUNCATE by DELETE statements

Note: if not already implemented, work tables should be cleaned as well when running the cleanup command.

**Comment by pjlammertyn** [comment]
This is incorrect!
Before the cleanup, riab disables all the constraints: https://github.com/RADar-AZDelta/Rabbit-in-a-Blender/blob/main/src/riab/etl/sql_server/cleanup.py#L32

Riab is not aware if you add additional constraints.
