### ISSUE TITLE
Implementation of era_tables

### ISSUE THREAD

**Issue by annabel-uzl** [RADar-AZDelta/Rabbit-in-a-Blender#93]
I looked into the implementation of the era tables and used the scripts Ohdsi defined online: https://ohdsi.github.io/CommonDataModel/sqlScripts.html#Era_Tables 
However, when I ran the etl (e.g. riab --run-etl ./omop-cdm --table condition_era), I got the following error:
 
`error: argument -t/--table: invalid choice: 'condition_era' (choose from 'metadata', 'cdm_source', 'vocabulary', 'location', 'care_site', 'provider', 'person', 'observation_period', 'visit_occurrence', 'visit_detail', 'condition_occurrence', 'drug_exposure', 'procedure_occurrence', 'device_exposure', 'measurement', 'observation', 'death', 'note', 'note_nlp', 'specimen', 'fact_relationship', 'payer_plan_period', 'cost', 'episode', 'episode_event')`
 
It seems like the _era tables are not implemented in the etl? Can they be added?

**Comment by pjlammertyn** [comment]
CLI aangepast, en ook de ETL flow:

![image](https://github.com/user-attachments/assets/0b26d3ca-cb8b-424b-a833-9c4bb3889cc6)
