### ISSUE TITLE
Reasoning behind era tables occuring before the occurence tables

### ISSUE THREAD

**Issue by annabel-uzl** [RADar-AZDelta/Rabbit-in-a-Blender#94]
We keep getting stuck on the reasoning of why the era tables appear before the occurence tables in the etl flow
![image](https://github.com/user-attachments/assets/a7451b60-818b-4b4b-806c-3001b105047d)

We understand it is an iterative process, but won't the era table always use the data of the occurence table of the _previous_ iteration? And thus be one iteration behind each time?

**Comment by pjlammertyn** [comment]
No reason, just a bug in the CSV of OHDSI, where the foreign key is not correctly set.

https://github.com/RADar-AZDelta/Rabbit-in-a-Blender/blob/main/src/riab/etl/etl_base.py#L183-L186
