### ISSUE TITLE
Parquet files in bucket not found due to backslash

### ISSUE THREAD

**Issue by annabel-uzl** [RADar-AZDelta/Rabbit-in-a-Blender#97]
The files in the bucket cannot be found anymore due to use of backslash instead of forward slash.
Temporary solution is to rename and move the files once they appear in the bucket (but the concepts will not be swapped)

![image](https://github.com/user-attachments/assets/f22c55ef-97a2-4a71-a32a-53baa7476031)

**Comment by pjlammertyn** [comment]
Did you use the correct uri format for the bucket?
'gs://{bucket_name}/{bucket_path}'

ex: 
```ini
[bigquery]
bucket=gs://my_riab_bucket/upload
```

**Comment by annabel-uzl** [comment]
Yes: 
![image](https://github.com/user-attachments/assets/91600ef9-95e9-4e8c-aa7e-ada7ad6383a4)

I did not have any problems previously and i did not change anything to my ini file. I do use Windows.

**Comment by pjlammertyn** [comment]
I can't simulate this problem.
In the [code](https://github.com/RADar-AZDelta/Rabbit-in-a-Blender/blob/main/src/riab/etl/bigquery/gcp.py#L191), the blob name is also generated by using Pythons buildin [Path.name](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.name) function. This function doesn't generate a \ character.
